trigger: none

pr:
  autoCancel: true
  drafts: false
  branches:
    include:
      - master
  paths:
    include:
      - neural_compressor
      - test
      - setup.py
      - requirements.txt
      - .azure-pipelines/scripts/ut
    exclude:
      - test/neural_coder

pool: ICX-16C

variables:
  IMAGE_NAME: "neural-compressor"
  IMAGE_TAG: "py38"
  UPLOAD_PATH: $(Build.SourcesDirectory)/log_dir
  DOWNLOAD_PATH: $(Build.SourcesDirectory)/log_dir
  ARTIFACT_NAME: "UT_report"
  REPO: $(Build.Repository.Uri)

stages:
  - stage: Adaptor
    displayName: Unit Test FWKs adaptor
    dependsOn: []
    jobs:
      - job:
        steps:
          - template: template/ut-template.yml
            parameters:
              dockerConfigName: "commonDockerConfig"
              utScriptFileName: "run_basic_adaptor"
              uploadPath: $(UPLOAD_PATH)
              utArtifact: "ut-adaptor"
              utTestMode: "no-coverage"
              utContainerName: "utTest-no-coverage"

  - stage: API
    displayName: User facing API
    dependsOn: []
    jobs:
      - job:
        steps:
          - template: template/ut-template.yml
            parameters:
              dockerConfigName: "commonDockerConfig"
              utScriptFileName: "run_basic_api"
              uploadPath: $(UPLOAD_PATH)
              utArtifact: "ut-coverage-api"
              utTestMode: "no-coverage"
              utContainerName: "utTest-no-coverage"

  - stage: Pruning
    displayName: Unit Test Pruning
    dependsOn: []
    jobs:
      - job:
        displayName: PyTorch Pruning
        steps:
          - template: template/ut-template.yml
            parameters:
              dockerConfigName: "commonDockerConfig"
              utScriptFileName: "run_basic_pt_pruning"
              uploadPath: $(UPLOAD_PATH)
              utArtifact: "ut-coverage-pt-pruning"
              utTestMode: "no-coverage"
              utContainerName: "utTest-no-coverage"
      - job:
        displayName: TensorFlow Pruning
        steps:
          - template: template/ut-template.yml
            parameters:
              dockerConfigName: "commonDockerConfig"
              utScriptFileName: "run_basic_tf_pruning"
              uploadPath: $(UPLOAD_PATH)
              utArtifact: "ut-coverage-tf-pruning"
              utTestMode: "no-coverage"
              utContainerName: "utTest-no-coverage"

  - stage: Others
    displayName: Unit Test other basic case
    dependsOn: []
    jobs:
      - job:
        steps:
          - template: template/ut-template.yml
            parameters:
              dockerConfigName: "commonDockerConfig"
              utScriptFileName: "run_basic_others"
              uploadPath: $(UPLOAD_PATH)
              utArtifact: "ut-others"
              utTestMode: "no-coverage"
              utContainerName: "utTest-no-coverage"

