trigger: none

pr:
  branches:
    include:
    - master
  paths:
    include:
    - neural_coder

pool: ICX-16C

parameters:
- name: nCoderContainerName
  type: string
  default: 'nCoderContainer'

stages:
- stage:
  displayName: Unit Test for Neural Coder
  jobs:
  - job:
    steps:
      - template: template/docker-template.yml
        parameters:
          repoName: 'neural-compressor'
          repoTag: 'py38'
          dockerFileName: 'Dockerfile'
          containerConfigName: 'commonContainer'
          containerName: ${{ parameters.nCoderContainerName }}

    - script: |
        docker exec ${{ parameters.nCoderContainerName }} bash -c "cd /neural-compressor/.azure-pipelines/scripts \
        && bash install_nc_full.sh \
        && bash ut/run_ncoder.sh"
      displayName: 'Install Neural Compressor and run UT'