trigger: none

pr:
  autoCancel: true
  drafts: false
  branches:
    include:
      - master
  paths:
    include:
      - neural_insights
      - setup.py

pool: ICX-16C

variables:
  UPLOAD_PATH: $(Build.SourcesDirectory)/log_dir

stages:
  - stage:
    displayName: Unit Test for Neural Insights
    jobs:
      - job:
        steps:
          - template: template/ut-template.yml
            parameters:
              dockerConfigName: 'commonDockerConfig'
              utScriptFileName: 'run_neural_insights'
              uploadPath: $(UPLOAD_PATH)
              utArtifact: 'ut-neural-insights'
              utContainerName: "utTest-nInsights"
