trigger: none

pr:
  branches:
    include:
    - master
  paths:
    include:
    - neural_compressor/ux

pool: ICX-16C

parameters:
- name: UXContainerName
  type: string
  default: 'UXContainer'

stages:
- stage:
  displayName: Unit Test for UX
  jobs:
  - job:
    steps:
      - template: template/docker-template.yml
        parameters:
          repoName: 'neural-compressor'
          repoTag: 'py38'
          dockerFileName: 'Dockerfile'
          containerConfigName: 'commonContainer'
          containerName: ${{ parameters.UXContainerName }}

    - script: |
        docker exec ${{ parameters.UXContainerName }} bash -c "cd /neural-compressor/.azure-pipelines/scripts \
        && bash install_nc_full.sh \
        && bash ut/run_ux.sh"
      displayName: 'Install Neural Compressor and run UT'