trigger: none

pr:
  branches:
    include:
    - master
  paths:
    include:
    - neural_compressor/ux

pool: ICX-16C

variables:
  UX_CONTAINER_NAME: 'UXContainer'

stages:
- stage:
  displayName: Unit Test for UX
  jobs:
  - job:
    steps:
      - template: template/docker-template.yml
        parameters:
          dockerConfigName: 'commonDockerConfig'
          repoName: 'neural-compressor'
          repoTag: 'py38'
          dockerFileName: 'Dockerfile'
          containerName: $(UX_CONTAINER_NAME)

      - script: |
          docker exec $(UX_CONTAINER_NAME) bash -c "cd /neural-compressor/.azure-pipelines/scripts \
          && bash install_nc_full.sh \
          && bash ut/run_ux.sh"
        displayName: 'Install Neural Compressor and run UT'