name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Online Document
      run: |
        git config --local --get remote.origin.url
        cd docs/build_docs
        bash build.sh latest
