name: Scanner BDBA

on:
  workflow_dispatch:
    repos:
      description: 'Enter Project repo for which you want to run coverity scan:'
      required: true
      type: string
      default: frameworks.ai.lpot.intel-lpot
    ref_name:
      description: 'Enter Project branch, tag:'
      required: true
      type: string
      default: master

jobs:
  bdba_job:
    name: BDBA Scan
    uses: intel-innersource/frameworks.ai.infrastructure.code-scan-tools/.github/workflows/Scanner_Bdba.yml@one-ci-cd
    with:
      repos: ${{ github.repos }}
      refs: ${{ github.ref_name }}
      group: "22"
      runners: "['self-hosted']"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      BDBA_TOKEN: ${{ secrets.BDBA_TOKEN }}